// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'core/connection_registry.dart';
import 'core/sync_engine/engine.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Stream<SyncEvent> initApp() => RustLib.instance.api.crateApiInitApp();

Future<List<String>> registerKeys(
        {required List<int> signingKeyBytes, required List<int> dhKeyBytes}) =>
    RustLib.instance.api.crateApiRegisterKeys(
        signingKeyBytes: signingKeyBytes, dhKeyBytes: dhKeyBytes);

Future<void> startSync(
        {required String storageDir,
        required String deviceName,
        required String platform,
        required String deviceId}) =>
    RustLib.instance.api.crateApiStartSync(
        storageDir: storageDir,
        deviceName: deviceName,
        platform: platform,
        deviceId: deviceId);

Future<void> handleAppForeground() =>
    RustLib.instance.api.crateApiHandleAppForeground();

Future<void> handleAppBackground() =>
    RustLib.instance.api.crateApiHandleAppBackground();

Future<void> sendLocalClipboardUpdate({required String content}) =>
    RustLib.instance.api.crateApiSendLocalClipboardUpdate(content: content);

Future<String> getDeviceId() => RustLib.instance.api.crateApiGetDeviceId();

Future<List<Peer>> getDiscoveredPeers() =>
    RustLib.instance.api.crateApiGetDiscoveredPeers();

Future<List<TrustedPeer>> getTrustedPeers() =>
    RustLib.instance.api.crateApiGetTrustedPeers();

Future<void> initiatePairing({required String peerId}) =>
    RustLib.instance.api.crateApiInitiatePairing(peerId: peerId);

Future<void> approvePairing({required String peerId, required bool approve}) =>
    RustLib.instance.api
        .crateApiApprovePairing(peerId: peerId, approve: approve);

Future<void> unpairDevice({required String peerId}) =>
    RustLib.instance.api.crateApiUnpairDevice(peerId: peerId);

class TrustedPeer {
  final String deviceId;
  final String deviceName;
  final String fingerprint;
  final BigInt pairedAt;

  const TrustedPeer({
    required this.deviceId,
    required this.deviceName,
    required this.fingerprint,
    required this.pairedAt,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      deviceName.hashCode ^
      fingerprint.hashCode ^
      pairedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrustedPeer &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          fingerprint == other.fingerprint &&
          pairedAt == other.pairedAt;
}
