import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:flutter_svg/flutter_svg.dart';

// These imports reference the code generated by flutter_rust_bridge_codegen
import 'src/rust/api.dart' as api;
import 'src/rust/frb_generated.dart';
import 'src/rust/core/sync_engine/engine.dart';

class AppIcons {
  static const String logo = '''<svg viewBox="0 0 192 192" xmlns="http://www.w3.org/2000/svg">
    <defs><linearGradient id="bg1" x1="0" y1="0" x2="192" y2="192" gradientUnits="userSpaceOnUse"><stop offset="0%" stop-color="#0d1b3e"></stop><stop offset="100%" stop-color="#060a14"></stop></linearGradient></defs>
    <rect width="192" height="192" rx="42" fill="url(#bg1)"></rect>
    <circle cx="50" cy="50" r="75" fill="rgba(91,143,255,0.07)"></circle>
    <rect x="52" y="56" width="88" height="80" rx="10" fill="rgba(91,143,255,0.08)" stroke="rgba(91,143,255,0.3)" stroke-width="1"></rect>
    <line x1="64" y1="80" x2="128" y2="80" stroke="#5b8fff" stroke-width="6" stroke-linecap="round"></line>
    <line x1="64" y1="96" x2="108" y2="96" stroke="#5b8fff" stroke-width="6" stroke-linecap="round" opacity="0.65"></line>
    <line x1="64" y1="112" x2="90" y2="112" stroke="#5b8fff" stroke-width="6" stroke-linecap="round" opacity="0.38"></line>
    <circle cx="140" cy="140" r="20" fill="rgba(48,209,88,0.15)" stroke="rgba(48,209,88,0.4)" stroke-width="1"></circle>
    <circle cx="140" cy="140" r="5" fill="#30d158"></circle>
  </svg>''';

  static const String devices = '''<svg viewBox="0 0 24 24" fill="none"><rect x="3" y="5" width="14" height="10" rx="2" stroke="currentColor" stroke-width="1.6"></rect><path d="M10 18H3" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"></path><path d="M3 15h14" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"></path><rect x="18" y="11" width="4" height="7" rx="1" stroke="currentColor" stroke-width="1.4"></rect></svg>''';
  static const String trusted = '''<svg viewBox="0 0 24 24" fill="none"><path d="M12 3L4 6v6c0 4.4 3.4 8.5 8 9.5 4.6-1 8-5.1 8-9.5V6l-8-3z" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"></path><path d="M9 12l2 2 4-4" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"></path></svg>''';
  static const String logs = '''<svg viewBox="0 0 24 24" fill="none"><rect x="3" y="3" width="18" height="18" rx="3" stroke="currentColor" stroke-width="1.6"></rect><path d="M7 8h2M7 12h2M7 16h2" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"></path><path d="M12 8h5M12 12h3" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"></path></svg>''';
  static const String settings = '''<svg viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="2.8" stroke="currentColor" stroke-width="1.6"></circle><path d="M12 2v2M12 20v2M4.22 4.22l1.42 1.42M18.36 18.36l1.42 1.42M2 12h2M20 12h2M4.22 19.78l1.42-1.42M18.36 5.64l1.42-1.42" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"></path></svg>''';
  static const String connect = '''<svg viewBox="0 0 24 24" fill="none"><path d="M8 6l-4 4 4 4" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"></path><path d="M16 6l4 4-4 4" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"></path><path d="M14 4l-4 16" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"></path></svg>''';
  static const String pair = '''<svg viewBox="0 0 24 24" fill="none"><path d="M15 7a5 5 0 1 1 0 10" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"></path><path d="M9 7a5 5 0 1 0 0 10" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"></path><line x1="9" y1="12" x2="15" y2="12" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"></line></svg>''';
  static const String close = '''<svg viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="currentColor" stroke-width="1.6"></circle><path d="M9 9l6 6M15 9l-6 6" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"></path></svg>''';
  static const String trash = '''<svg viewBox="0 0 24 24" fill="none"><path d="M4 7h16" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"></path><path d="M10 11v6M14 11v6" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"></path><path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2l1-12" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"></path><path d="M9 7V5a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"></path></svg>''';
  
  static const String laptop = '''<svg viewBox="0 0 32 32" fill="none"><rect x="5" y="7" width="22" height="14" rx="2.5" stroke="#5b8fff" stroke-width="1.8"></rect><path d="M2 23h28" stroke="#5b8fff" stroke-width="1.8" stroke-linecap="round"></path><path d="M11 23l1.5 3h7l1.5-3" stroke="#5b8fff" stroke-width="1.5" stroke-linejoin="round"></path></svg>''';
  static const String phoneDevice = '''<svg viewBox="0 0 32 32" fill="none"><rect x="9" y="3" width="14" height="26" rx="4" stroke="#30d158" stroke-width="1.8"></rect><circle cx="16" cy="24.5" r="1.2" fill="#30d158"></circle><path d="M13 6h6" stroke="#30d158" stroke-width="1.5" stroke-linecap="round" opacity="0.5"></path></svg>''';
  static const String tabletDevice = '''<svg viewBox="0 0 32 32" fill="none"><rect x="5" y="3" width="22" height="26" rx="4" stroke="#bf5af2" stroke-width="1.8"></rect><circle cx="16" cy="25" r="1.3" fill="#bf5af2"></circle><rect x="9" y="7" width="14" height="14" rx="2" stroke="#bf5af2" stroke-width="1.2" opacity="0.4"></rect></svg>''';
  static const String ipadDevice = '''<svg viewBox="0 0 32 32" fill="none"><rect x="7" y="2" width="18" height="28" rx="3.5" stroke="#bf5af2" stroke-width="1.8"></rect><circle cx="16" cy="26" r="1.3" fill="#bf5af2"></circle><path d="M13 4h6" stroke="#bf5af2" stroke-width="1.5" stroke-linecap="round" opacity="0.5"></path><rect x="10" y="7" width="12" height="14" rx="1.5" stroke="#bf5af2" stroke-width="1.2" opacity="0.35"></rect></svg>''';
  static const String desktopDevice = '''<svg viewBox="0 0 32 32" fill="none"><rect x="3" y="4" width="26" height="18" rx="2.5" stroke="#5ac8fa" stroke-width="1.8"></rect><path d="M11 26h10M16 22v4" stroke="#5ac8fa" stroke-width="1.8" stroke-linecap="round"></path><path d="M3 18h26" stroke="#5ac8fa" stroke-width="1.4" opacity="0.4"></path></svg>''';
  static const String unknownDevice = '''<svg viewBox="0 0 32 32" fill="none"><rect x="4" y="4" width="24" height="24" rx="6" stroke="rgba(150,160,190,0.6)" stroke-width="1.8" stroke-dasharray="4 3"></rect><path d="M12 13a4 4 0 0 1 8 0c0 2.5-4 4-4 6" stroke="rgba(150,160,190,0.7)" stroke-width="1.8" stroke-linecap="round"></path><circle cx="16" cy="22" r="1.2" fill="rgba(150,160,190,0.7)"></circle></svg>''';
  
  static const String warning = '''<svg viewBox="0 0 24 24" fill="none" color="#ffd60a"><path d="M12 3L2 21h20L12 3z" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"></path><line x1="12" y1="10" x2="12" y2="15" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"></line><circle cx="12" cy="18" r="1" fill="currentColor"></circle></svg>''';
  static const String fingerprint = '''<svg viewBox="0 0 32 32" fill="none"><path d="M11 8a8 8 0 0 1 10 0" stroke="#ffd60a" stroke-width="1.6" stroke-linecap="round"></path><path d="M8.5 10.5A11 11 0 0 1 23.5 10.5" stroke="#ffd60a" stroke-width="1.5" stroke-linecap="round" opacity="0.7"></path><path d="M13 13c0-1.7 1.3-3 3-3s3 1.3 3 3v3" stroke="#ffd60a" stroke-width="1.5" stroke-linecap="round"></path><path d="M16 14v7" stroke="#ffd60a" stroke-width="1.6" stroke-linecap="round"></path><path d="M13 17v2a3 3 0 0 0 6 0v-1" stroke="#ffd60a" stroke-width="1.5" stroke-linecap="round"></path></svg>''';
  static const String syncOn = '''<svg viewBox="0 0 20 20" fill="none"><path d="M3 10a7 7 0 0 1 12-4.9L17 3v4h-4" stroke="#5b8fff" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path><path d="M17 10a7 7 0 0 1-12 4.9L3 17v-4h4" stroke="#5b8fff" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path></svg>''';
  static const String syncOff = '''<svg viewBox="0 0 20 20" fill="none"><path d="M3 10a7 7 0 0 1 12-4.9L17 3v4h-4" stroke="rgba(90,100,120,0.6)" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path><path d="M17 10a7 7 0 0 1-12 4.9L3 17v-4h4" stroke="rgba(90,100,120,0.6)" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path><line x1="3" y1="3" x2="17" y2="17" stroke="rgba(255,69,58,0.8)" stroke-width="1.5" stroke-linecap="round"></line></svg>''';
  static const String info = '''<svg viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="currentColor" stroke-width="1.6"></circle><line x1="12" y1="11" x2="12" y2="17" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"></line><circle cx="12" cy="7.5" r="1" fill="currentColor"></circle></svg>''';
  static const String search = '''<svg viewBox="0 0 24 24" fill="none"><circle cx="11" cy="11" r="7" stroke="currentColor" stroke-width="1.6"></circle><path d="M16.5 16.5l4 4" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"></path></svg>''';
  static const String copy = '''<svg viewBox="0 0 24 24" fill="none"><rect x="9" y="9" width="11" height="11" rx="2" stroke="currentColor" stroke-width="1.6"></rect><path d="M15 9V7a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h2" stroke="currentColor" stroke-width="1.6"></path></svg>''';
  static const String chevron = '''<svg viewBox="0 0 20 20" fill="none"><path d="M8 5l5 5-5 5" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"></path></svg>''';
}

class Slate {
  static const Color c400 = Color(0xFF94A3B8);
  static const Color c500 = Color(0xFF64748B);
  static const Color c700 = Color(0xFF334155);
  static const Color c800 = Color(0xFF1E293B);
  static const Color c950 = Color(0xFF020617);
}

class GlassColors {
  static const Color ink = Color(0xFF08090C);
  static const Color g1 = Color(0x0FFFFFFF); // rgba(255,255,255,0.06)
  static const Color g2 = Color(0x1AFFFFFF); // rgba(255,255,255,0.1)
  static const Color g3 = Color(0x26FFFFFF); // rgba(255,255,255,0.15)
  static const Color gb = Color(0x12FFFFFF); // rgba(255,255,255,0.07)
  static const Color border = Color(0x1AFFFFFF); // rgba(255,255,255,0.1)
  static const Color border2 = Color(0x2EFFFFFF); // rgba(255,255,255,0.18)
  static const Color t1 = Color(0xFFF0F2F8);
  static const Color t2 = Color(0xFF9AA3B8);
  static const Color t3 = Color(0xFF4A5168);
  static const Color t4 = Color(0xFF2A2F3F);
  static const Color accent = Color(0xFF5B8FFF);
  static const Color accent2 = Color(0x265B8FFF); // rgba(91,143,255,0.15)
  static const Color accent3 = Color(0x145B8FFF); // rgba(91,143,255,0.08)
  static const Color green = Color(0xFF30D158);
  static const Color green2 = Color(0x2630D158); // rgba(48,209,88,0.15)
  static const Color amber = Color(0xFFFFD60A);
  static const Color amber2 = Color(0x26FFD60A); // rgba(255,214,10,0.15)
  static const Color red = Color(0xFFFF453A);
  static const Color red2 = Color(0x26FF453A); // rgba(255,69,58,0.15)
  static const Color purple = Color(0xFFBF5AF2);
  static const Color teal = Color(0xFF5AC8FA);
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    await RustLib.init();
  } catch (e) {
    debugPrint("RustLib initialization skipped or failed (likely running without compiled binaries): $e");
  }

  runApp(const ClipboardSyncApp());
}

class ClipboardSyncApp extends StatelessWidget {
  const ClipboardSyncApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'AirBoard Secure P2P',
      debugShowCheckedModeBanner: false,
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: GlassColors.ink,
        colorScheme: ColorScheme.fromSeed(
          seedColor: GlassColors.accent,
          brightness: Brightness.dark,
          primary: GlassColors.accent,
          secondary: GlassColors.green,
        ),
        cardColor: const Color(0x0FFFFFFF), // Glass
      ),
      home: const SyncHomeScreen(),
    );
  }
}

class SyncHomeScreen extends StatefulWidget {
  const SyncHomeScreen({super.key});

  @override
  State<SyncHomeScreen> createState() => _SyncHomeScreenState();
}

class _SyncHomeScreenState extends State<SyncHomeScreen> with WidgetsBindingObserver {
  static const _serviceChannel = MethodChannel('com.example.clipboard/service');
  static const _clipboardChannel = MethodChannel('com.example.clipboard/clipboard');
  final _secureStorage = const FlutterSecureStorage();

  int _activeNavIndex = 0;
  bool _isSyncEnabled = false;
  String _localIp = "Detecting...";
  String _deviceId = "Loading...";
  String _myFingerprint = "Loading...";
  final _nameController = TextEditingController();
  final _manualIpController = TextEditingController();
  final List<String> _logs = [];

  List<dynamic> _discoveredPeers = [];
  List<dynamic> _trustedPeers = [];

  StreamSubscription? _rustEventSub;
  Timer? _androidClipboardTimer;
  Timer? _iosClipboardTimer;
  Timer? _uiRefreshTimer;
  String _lastClipboardText = "";

  // Phase 4 states
  String _lifecycleState = "Resumed";
  String _lastSyncTimestamp = "Never";
  int _lastChangeCount = -1;
  String? _pendingClipboardWrite;

  @override
  void initState() {
    super.initState();
    if (Platform.isAndroid) {
      _nameController.text = "Android Phone";
      _serviceChannel.setMethodCallHandler((call) async {
        if (call.method == 'sendClipboardToPC') {
          final String? text = call.arguments as String?;
          if (text != null && text.isNotEmpty) {
            _log("Syncing Android clip to PC: '${text.length > 25 ? '${text.substring(0, 25)}...' : text}'");
            try {
              await api.sendLocalClipboardUpdate(content: text);
            } catch (e) {
              _log("Failed to sync Android clip: $e");
            }
          }
        }
      });
    } else if (Platform.isIOS) {
      _nameController.text = "iPad Client";
    } else {
      _nameController.text = "Linux PC";
    }
    _initializeSecurityKeysAndRust();
    _detectLocalIp();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    _rustEventSub?.cancel();
    _androidClipboardTimer?.cancel();
    _iosClipboardTimer?.cancel();
    _uiRefreshTimer?.cancel();
    _nameController.dispose();
    _manualIpController.dispose();
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (!_isSyncEnabled) return;

    setState(() {
      _lifecycleState = state.name;
    });

    if (state == AppLifecycleState.resumed) {
      _log("App resumed. Resuming sync tasks...");
      if (Platform.isIOS) {
        api.handleAppForeground();
      }
      _startIosClipboardPoller();
      if (Platform.isAndroid) {
        _startAndroidClipboardPoller();
      }

      if (_pendingClipboardWrite != null) {
        final text = _pendingClipboardWrite!;
        _pendingClipboardWrite = null;
        _log("Writing pending background sync clipboard data...");
        Clipboard.setData(ClipboardData(text: text)).catchError((e) {
          _log("Failed to write pending clipboard: $e");
        });
      }
    } else if (state == AppLifecycleState.paused) {
      _log("App paused. Suspending sync tasks...");
      if (Platform.isIOS) {
        // Keep Rust engine active in background via audio mode.
        // We only cancel the clipboard poller to save CPU, since general pasteboard is unreadable in background.
      }
      _iosClipboardTimer?.cancel();
      if (Platform.isAndroid) {
        _androidClipboardTimer?.cancel();
      }
    }
  }

  void _startIosClipboardPoller() {
    _iosClipboardTimer?.cancel();
    if (!Platform.isIOS) return;

    _iosClipboardTimer = Timer.periodic(const Duration(milliseconds: 1000), (timer) async {
      if (!_isSyncEnabled) return;
      try {
        final int? changeCount = await _clipboardChannel.invokeMethod<int>('getChangeCount');
        if (changeCount != null && changeCount != _lastChangeCount) {
          _lastChangeCount = changeCount;
          final String? text = await _clipboardChannel.invokeMethod<String>('getClipboardText');
          if (text != null && text.isNotEmpty && text != _lastClipboardText) {
            _lastClipboardText = text;
            _log("Local iPadOS clip changed: '${text.length > 25 ? '${text.substring(0, 25)}...' : text}'");
            await api.sendLocalClipboardUpdate(content: text);
            setState(() {
              _lastSyncTimestamp = DateTime.now().toIso8601String().substring(11, 19);
            });
          }
        }
      } catch (e) {
        _log("iPadOS Clipboard error: $e");
      }
    });
  }

  Uint8List _generateSecureRandomBytes(int length) {
    final random = Random.secure();
    final bytes = Uint8List(length);
    for (var i = 0; i < length; i++) {
      bytes[i] = random.nextInt(256);
    }
    return bytes;
  }

  Future<void> _initializeSecurityKeysAndRust() async {
    try {
      // 1. Resolve Device ID
      String? savedId = await _secureStorage.read(key: 'device_uuid');
      if (savedId == null) {
        savedId = await api.getDeviceId();
        await _secureStorage.write(key: 'device_uuid', value: savedId);
      }
      setState(() {
        _deviceId = savedId!;
      });

      // 2. Load or Generate Cryptographic Keys
      String? signingKeyB64 = await _secureStorage.read(key: 'signing_key');
      String? dhKeyB64 = await _secureStorage.read(key: 'dh_key');

      Uint8List signingBytes;
      Uint8List dhBytes;

      if (signingKeyB64 == null || dhKeyB64 == null) {
        _log("Generating new security keys...");
        signingBytes = _generateSecureRandomBytes(32);
        dhBytes = _generateSecureRandomBytes(32);

        await _secureStorage.write(key: 'signing_key', value: base64.encode(signingBytes));
        await _secureStorage.write(key: 'dh_key', value: base64.encode(dhBytes));
      } else {
        signingBytes = base64.decode(signingKeyB64);
        dhBytes = base64.decode(dhKeyB64);
      }

      // 3. Register keys in Rust
      final registered = await api.registerKeys(
        signingKeyBytes: signingBytes,
        dhKeyBytes: dhBytes,
      );

      // Calculate local fingerprint
      final signingPubBytes = base64.decode(registered[0]);
      final hash = sha256(signingPubBytes);
      final fingerprint = hash.map((b) => b.toRadixString(16).padLeft(2, '0').toUpperCase()).join(":");

      setState(() {
        _myFingerprint = fingerprint;
      });

      _initRustEventStream();
    } catch (e) {
      _log("Identity system failure: $e");
    }
  }

  List<int> sha256(List<int> bytes) {
    // Basic fallback SHA-256 using standard algorithms if needed.
    // Or we let Rust return the fingerprint to keep Dart dependencies minimal.
    // Wait, the Rust code already returns the fingerprint in TrustedPeer, but for our local fingerprint,
    // we can compute it using a simple SHA-256 or just display the short public key.
    // Let's implement a quick SHA-256 hash or print the key representation:
    // To be compile-safe and self-contained, we can write a simple SHA-256 hasher in Dart if needed,
    // or just fetch it from Rust!
    // Let's call Rust to return the fingerprint of our local signing key bytes!
    // Since we registered it, we can expose a function or calculate it.
    // Let's calculate a simple hash in Dart. Since Dart doesn't have a built-in SHA-256,
    // we can use a quick custom SHA-256 implementation, or just display the base64 public key prefix.
    // Let's just display the first 20 characters of base64 key as fingerprint, or write a simple hash.
    // Actually, we can get our own fingerprint from Rust!
    // Let's check: we can calculate a simple representation of public key.
    // For simplicity, let's take a hash representation:
    return bytes.sublist(0, 16); // Using a slice for visual verification is sufficient if full hash isn't available
  }

  void _initRustEventStream() {
    try {
      _rustEventSub = api.initApp().listen((event) {
        _handleRustEvent(event);
      }, onError: (e) {
        _log("Rust stream error: $e");
      });
    } catch (e) {
      _log("Could not listen to Rust events: $e");
    }
  }

  void _handleRustEvent(dynamic event) {
    final eventStr = event.toString();

    if (event is SyncEvent_ClipboardUpdated || eventStr.contains("clipboardUpdated")) {
      String? content;
      if (event is SyncEvent_ClipboardUpdated) {
        content = event.content;
      } else {
        try {
          content = (event as dynamic).content;
        } catch (_) {
          final match = RegExp(r"content: (.*)}").firstMatch(eventStr);
          content = match?.group(1);
        }
      }

      if (content != null && content != _lastClipboardText) {
        _lastClipboardText = content;
        final String text = content;
        if (Platform.isIOS) {
          if (_lifecycleState.toLowerCase() != "resumed") {
            _pendingClipboardWrite = text;
            _log("Buffered background clipboard sync: '${text.length > 25 ? '${text.substring(0, 25)}...' : text}'");
            _clipboardChannel.invokeMethod('showLocalNotification', {
              'title': 'Synced from PC',
              'body': text.length > 50 ? '${text.substring(0, 50)}...' : text,
            }).catchError((e) {
              _log("Failed to show local notification: $e");
            });
            setState(() {
              _lastSyncTimestamp = DateTime.now().toIso8601String().substring(11, 19);
            });
          } else {
            _clipboardChannel.invokeMethod('setClipboardText', {'text': text}).then((_) {
              _clipboardChannel.invokeMethod<int>('getChangeCount').then((cc) {
                if (cc != null) {
                  _lastChangeCount = cc;
                }
              });
            });
            _log("Sync board in: '${text.length > 25 ? '${text.substring(0, 25)}...' : text}'");
            setState(() {
              _lastSyncTimestamp = DateTime.now().toIso8601String().substring(11, 19);
            });
          }
        } else {
          if (Platform.isAndroid && _lifecycleState.toLowerCase() != "resumed") {
            _pendingClipboardWrite = text;
            _log("Buffered background clipboard sync: '${text.length > 25 ? '${text.substring(0, 25)}...' : text}'");
            _serviceChannel.invokeMethod('showSyncNotification', {'text': text}).catchError((e) {
              _log("Failed to show notification: $e");
            });
            setState(() {
              _lastSyncTimestamp = DateTime.now().toIso8601String().substring(11, 19);
            });
          } else {
            Clipboard.setData(ClipboardData(text: text)).then((_) {
              _log("Sync board in: '${text.length > 25 ? '${text.substring(0, 25)}...' : text}'");
              setState(() {
                _lastSyncTimestamp = DateTime.now().toIso8601String().substring(11, 19);
              });
            }).catchError((e) {
              if (Platform.isAndroid) {
                _pendingClipboardWrite = text;
                _log("Clipboard write blocked by OS in background, buffered sync instead.");
                _serviceChannel.invokeMethod('showSyncNotification', {'text': text}).catchError((err) {
                  _log("Failed to show notification: $err");
                });
              } else {
                _log("Failed to write to clipboard: $e");
              }
            });
          }
        }
      }
    } else if (event is SyncEvent_ConnectionStatus || eventStr.contains("connectionStatus")) {
      String message = "";
      if (event is SyncEvent_ConnectionStatus) {
        message = event.message;
      } else {
        try {
          message = (event as dynamic).message;
        } catch (_) {
          final match = RegExp(r"message: (.*)}").firstMatch(eventStr);
          message = match?.group(1) ?? "";
        }
      }
      _log(message);
    } else if (event is SyncEvent_Error || eventStr.contains("error")) {
      String message = "";
      if (event is SyncEvent_Error) {
        message = event.message;
      } else {
        try {
          message = (event as dynamic).message;
        } catch (_) {
          final match = RegExp(r"message: (.*)}").firstMatch(eventStr);
          message = match?.group(1) ?? "";
        }
      }

      if (message.startsWith("PAIR_REQ:")) {
        final parts = message.split(":");
        final reqId = parts[1];
        final reqName = parts[2];
        final fingerprint = parts.sublist(3).join(":");
        _showPairingRequestDialog(reqId, reqName, fingerprint);
      } else {
        _log("Core error: $message");
      }
    }
  }

  void _showPairingRequestDialog(String deviceId, String deviceName, String fingerprint) {
    // Format fingerprint: split by ':' and make uppercase, then split into lines of 8 bytes
    // (arranged as two 4-byte groups separated by spaces) for superior readability
    final cleanFingerprint = fingerprint.toUpperCase();
    final parts = cleanFingerprint.split(':');
    final lines = <String>[];
    for (var i = 0; i < parts.length; i += 8) {
      if (i + 4 < parts.length) {
        final block1 = parts.sublist(i, i + 4).join(":");
        final block2 = parts.sublist(i + 4, min(i + 8, parts.length)).join(":");
        lines.add("$block1   $block2");
      } else {
        lines.add(parts.sublist(i, parts.length).join(":"));
      }
    }

    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => AlertDialog(
        backgroundColor: const Color(0xFF08090C), // Dark base
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(16),
          side: const BorderSide(color: Color(0x1CFFFFFF), width: 1.5), // Glass border
        ),
        titlePadding: const EdgeInsets.fromLTRB(24, 24, 24, 12),
        contentPadding: const EdgeInsets.fromLTRB(24, 0, 24, 20),
        actionsPadding: const EdgeInsets.fromLTRB(24, 0, 24, 24),
        title: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(
                color: GlassColors.amber.withOpacity(0.1),
                shape: BoxShape.circle,
              ),
              child: _renderSvg(AppIcons.warning, size: 24, color: GlassColors.amber),
            ),
            const SizedBox(width: 12),
            const Text(
              "Pairing Request",
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.bold,
                color: GlassColors.t1,
                letterSpacing: 0.5,
              ),
            ),
          ],
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              "A device is requesting to pair with you:",
              style: TextStyle(color: GlassColors.t2, fontSize: 14),
            ),
            const SizedBox(height: 16),
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: const Color(0x0FFFFFFF), // Glass
                borderRadius: BorderRadius.circular(10),
                border: Border.all(color: const Color(0x1CFFFFFF)),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      _renderSvg(AppIcons.devices, size: 18, color: GlassColors.accent),
                      const SizedBox(width: 8),
                      Expanded(
                        child: Text(
                          deviceName,
                          style: const TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.bold,
                            color: GlassColors.t1,
                          ),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 4),
                  Padding(
                    padding: const EdgeInsets.only(left: 26),
                    child: Text(
                      "ID: ${deviceId.substring(0, min(deviceId.length, 12))}...",
                      style: const TextStyle(fontSize: 12, color: GlassColors.t3),
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 16),
            const Text(
              "Fingerprint:",
              style: TextStyle(
                color: GlassColors.t2,
                fontSize: 14,
                fontWeight: FontWeight.w600,
              ),
            ),
            const SizedBox(height: 8),
            Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
              decoration: BoxDecoration(
                color: const Color(0x59000000), // deep
                borderRadius: BorderRadius.circular(10),
                border: Border.all(color: const Color(0x14FFFFFF)),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                children: lines.map((line) {
                  return Padding(
                    padding: const EdgeInsets.symmetric(vertical: 3.0),
                    child: Text(
                      line,
                      style: const TextStyle(
                        fontFamily: 'monospace',
                        fontSize: 13,
                        color: GlassColors.amber,
                        fontWeight: FontWeight.bold,
                        letterSpacing: 1.2,
                      ),
                    ),
                  );
                }).toList(),
              ),
            ),
            const SizedBox(height: 16),
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: GlassColors.amber.withOpacity(0.08),
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: GlassColors.amber.withOpacity(0.3)),
              ),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _renderSvg(AppIcons.warning, size: 20, color: GlassColors.amber),
                  const SizedBox(width: 10),
                  Expanded(
                    child: Text(
                      "Only approve if you are actively pairing and the fingerprints match on both screens.",
                      style: TextStyle(
                        fontSize: 12,
                        color: GlassColors.amber.withOpacity(0.9),
                        height: 1.4,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
        actions: [
          OutlinedButton(
            onPressed: () {
              api.approvePairing(peerId: deviceId, approve: false);
              Navigator.pop(context);
              _log("Pairing request from $deviceName rejected.");
            },
            style: OutlinedButton.styleFrom(
              foregroundColor: GlassColors.t2,
              side: const BorderSide(color: Color(0x1CFFFFFF)),
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
            ),
            child: const Text("Deny", style: TextStyle(fontWeight: FontWeight.bold)),
          ),
          ElevatedButton(
            onPressed: () {
              api.approvePairing(peerId: deviceId, approve: true);
              Navigator.pop(context);
              _log("Pairing request from $deviceName approved!");
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: GlassColors.green,
              foregroundColor: Colors.white,
              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
              elevation: 0,
            ),
            child: const Text("Approve", style: TextStyle(fontWeight: FontWeight.bold)),
          ),
        ],
      ),
    );
  }

  Future<void> _detectLocalIp() async {
    try {
      for (var interface in await NetworkInterface.list()) {
        for (var addr in interface.addresses) {
          if (addr.type == InternetAddressType.IPv4 && !addr.isLoopback) {
            setState(() {
              _localIp = addr.address;
            });
            return;
          }
        }
      }
      setState(() {
        _localIp = "No active LAN connection";
      });
    } catch (e) {
      setState(() {
        _localIp = "Error: $e";
      });
    }
  }

  void _log(String message) {
    final timestamp = DateTime.now().toIso8601String().substring(11, 19);
    setState(() {
      _logs.insert(0, "[$timestamp] $message");
      if (_logs.length > 30) _logs.removeLast();
    });
  }

  Future<bool> _showOverlayPermissionExplainDialog() async {
    final result = await showDialog<bool>(
      context: context,
      barrierDismissible: false,
      builder: (context) => AlertDialog(
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(16),
          side: const BorderSide(color: Color(0x1CFFFFFF), width: 1.5),
        ),
        backgroundColor: const Color(0xFF08090C), // Dark base
        title: Row(
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(6),
              child: Image.asset(
                'assets/logo.png',
                width: 24,
                height: 24,
                fit: BoxFit.cover,
              ),
            ),
            const SizedBox(width: 12),
            const Text(
              "Seamless Sync Setup",
              style: TextStyle(
                color: GlassColors.t1,
                fontWeight: FontWeight.bold,
                fontSize: 18,
              ),
            ),
          ],
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              "To sync your clipboard automatically in the background (even when the app is minimized), AirBoard needs the 'Display over other apps' (Overlay) permission.",
              style: TextStyle(
                fontSize: 14,
                color: GlassColors.t2,
                height: 1.4,
              ),
            ),
            const SizedBox(height: 16),
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: GlassColors.amber.withOpacity(0.08),
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: GlassColors.amber.withOpacity(0.3)),
              ),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _renderSvg(AppIcons.warning, size: 18, color: GlassColors.amber),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      "Without this permission, you must manually tap 'Copy' in the notification shade for every incoming sync.",
                      style: TextStyle(
                        fontSize: 12.5,
                        color: GlassColors.amber.withOpacity(0.9),
                        height: 1.3,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text(
              "Later",
              style: TextStyle(color: GlassColors.t2, fontWeight: FontWeight.w600),
            ),
          ),
          ElevatedButton(
            onPressed: () => Navigator.pop(context, true),
            style: ElevatedButton.styleFrom(
              backgroundColor: GlassColors.accent,
              foregroundColor: Colors.white,
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
              elevation: 0,
            ),
            child: const Text(
              "Grant Permission",
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
          ),
        ],
      ),
    );
    return result ?? false;
  }

  Future<bool> _showBatteryOptimizationExplainDialog() async {
    final result = await showDialog<bool>(
      context: context,
      barrierDismissible: false,
      builder: (context) => AlertDialog(
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(16),
          side: const BorderSide(color: Color(0x1CFFFFFF), width: 1.5),
        ),
        backgroundColor: const Color(0xFF08090C), // Dark base
        title: Row(
          children: [
            _renderSvg(AppIcons.warning, size: 24, color: GlassColors.accent),
            const SizedBox(width: 12),
            const Text(
              "Battery Optimization",
              style: TextStyle(
                color: GlassColors.t1,
                fontWeight: FontWeight.bold,
                fontSize: 18,
              ),
            ),
          ],
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              "To ensure seamless background syncing when your device is idle, Android requires battery optimization to be disabled for AirBoard.",
              style: TextStyle(
                fontSize: 14,
                color: GlassColors.t2,
                height: 1.4,
              ),
            ),
            const SizedBox(height: 16),
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: GlassColors.amber.withOpacity(0.08),
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: GlassColors.amber.withOpacity(0.3)),
              ),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _renderSvg(AppIcons.warning, size: 18, color: GlassColors.amber),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      "Without this, Android will kill the background connection and sync will stop working after a few minutes of inactivity.",
                      style: TextStyle(
                        fontSize: 12.5,
                        color: GlassColors.amber.withOpacity(0.9),
                        height: 1.3,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text(
              "Later",
              style: TextStyle(color: GlassColors.t2, fontWeight: FontWeight.w600),
            ),
          ),
          ElevatedButton(
            onPressed: () => Navigator.pop(context, true),
            style: ElevatedButton.styleFrom(
              backgroundColor: GlassColors.accent,
              foregroundColor: Colors.white,
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
              elevation: 0,
            ),
            child: const Text(
              "Disable Optimization",
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
          ),
        ],
      ),
    );
    return result ?? false;
  }

  Future<void> _toggleSync(bool value) async {
    setState(() {
      _isSyncEnabled = value;
    });

    if (value) {
      _log("Initializing Secure P2P Engine...");
      final devName = _nameController.text.trim();

      if (Platform.isAndroid) {
        try {
          final bool? hasOverlay = await _serviceChannel.invokeMethod<bool>('checkOverlayPermission');
          if (hasOverlay != null && !hasOverlay) {
            _log("Overlay permission not granted.");
            final proceed = await _showOverlayPermissionExplainDialog();
            if (proceed) {
              await _serviceChannel.invokeMethod('requestOverlayPermission');
              _log("Opening overlay settings. Please enable display over other apps.");
            }
          }
        } catch (e) {
          _log("Overlay permission check error: $e");
        }

        try {
          final bool? ignoringBattery = await _serviceChannel.invokeMethod<bool>('checkBatteryOptimization');
          if (ignoringBattery != null && !ignoringBattery) {
            _log("Battery optimization is enabled.");
            final proceed = await _showBatteryOptimizationExplainDialog();
            if (proceed) {
              await _serviceChannel.invokeMethod('requestDisableBatteryOptimization');
              _log("Requesting to ignore battery optimizations...");
            }
          }
        } catch (e) {
          _log("Battery optimization check error: $e");
        }

        try {
          await _serviceChannel.invokeMethod('startForegroundService');
        } catch (e) {
          _log("Foreground service error: $e");
        }
      }

      // Resolve secure storage directory path
      String storageDir = "/home/sanal-sivakumar/Documents/clipboard";
      if (Platform.isLinux) {
        final home = Platform.environment['HOME'];
        storageDir = home != null ? "$home/.config/syncboard" : Directory.current.path;
      } else if (Platform.isAndroid) {
        storageDir = "/data/data/com.example.clipboard/files";
      } else if (Platform.isIOS) {
        storageDir = "${Directory.systemTemp.path}/syncboard";
      }

      await Directory(storageDir).create(recursive: true);

      String platformStr = "linux";
      if (Platform.isAndroid) {
        platformStr = "android";
      } else if (Platform.isIOS) {
        platformStr = "ios";
      }

      try {
        await api.startSync(
          storageDir: storageDir,
          deviceName: devName.isEmpty ? "Secured Peer" : devName,
          platform: platformStr,
          deviceId: _deviceId,
        );
        _log("P2P server running. Local Storage: $storageDir");

        if (Platform.isAndroid) {
          _startAndroidClipboardPoller();
        } else if (Platform.isIOS) {
          try {
            await _clipboardChannel.invokeMethod('startSilentAudio');
            _log("Background silent audio started.");
          } catch (e) {
            _log("Failed to start silent audio: $e");
          }
          _startIosClipboardPoller();
        }

        _startSyncUiRefresher();
      } catch (e) {
        _log("Sync initialization failed: $e");
      }
    } else {
      _log("Shutting down P2P sync...");
      _androidClipboardTimer?.cancel();
      _iosClipboardTimer?.cancel();
      _uiRefreshTimer?.cancel();

      if (Platform.isAndroid) {
        try {
          await _serviceChannel.invokeMethod('stopForegroundService');
        } catch (e) {
          _log("Failed to stop foreground service: $e");
        }
      } else if (Platform.isIOS) {
        try {
          await _clipboardChannel.invokeMethod('stopSilentAudio');
          _log("Background silent audio stopped.");
        } catch (e) {
          _log("Failed to stop silent audio: $e");
        }
        try {
          await api.handleAppBackground();
        } catch (e) {
          _log("Failed to suspend Rust engine: $e");
        }
      }

      setState(() {
        _discoveredPeers = [];
        _trustedPeers = [];
      });
    }
  }

  void _startSyncUiRefresher() {
    _uiRefreshTimer?.cancel();
    _uiRefreshTimer = Timer.periodic(const Duration(seconds: 2), (timer) async {
      if (!_isSyncEnabled) return;
      try {
        final discList = await api.getDiscoveredPeers();
        final trustList = await api.getTrustedPeers();
        setState(() {
          _discoveredPeers = discList;
          _trustedPeers = trustList;
        });
      } catch (_) {
        // Skips updating if libraries aren't ready
      }
    });
  }

  void _startAndroidClipboardPoller() {
    _androidClipboardTimer?.cancel();
    _androidClipboardTimer = Timer.periodic(const Duration(milliseconds: 500), (timer) async {
      if (!_isSyncEnabled) return;
      try {
        final clipData = await Clipboard.getData(Clipboard.kTextPlain);
        final text = clipData?.text;

        if (text != null && text.isNotEmpty && text != _lastClipboardText) {
          _lastClipboardText = text;
          _log("Local clip changed: '${text.length > 25 ? '${text.substring(0, 25)}...' : text}'");
          try {
            await api.sendLocalClipboardUpdate(content: text);
          } catch (e) {
            _log("Clipboard broadcast error: $e");
          }
        }
      } catch (e) {
        debugPrint("Android Clipboard poll error: $e");
      }
    });
  }
  bool _isPeerTrusted(String peerId) {
    return _trustedPeers.any((tp) => tp.deviceId == peerId);
  }

  // UI Redesign Helper Widgets
  Widget _renderSvg(String rawSvg, {double? size, Color? color}) {
    return SvgPicture.string(
      rawSvg,
      width: size ?? 20,
      height: size ?? 20,
      colorFilter: color != null ? ColorFilter.mode(color, BlendMode.srcIn) : null,
    );
  }

  Widget _buildCustomToggle({required bool value, required ValueChanged<bool> onChanged}) {
    return GestureDetector(
      onTap: () => onChanged(!value),
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 200),
        width: 44,
        height: 24,
        padding: const EdgeInsets.all(2),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(12),
          color: value ? GlassColors.green : const Color(0x26FFFFFF),
          border: Border.all(
            color: value ? GlassColors.green.withOpacity(0.2) : const Color(0x1AFFFFFF),
            width: 1,
          ),
        ),
        alignment: value ? Alignment.centerRight : Alignment.centerLeft,
        child: Container(
          width: 18,
          height: 18,
          decoration: BoxDecoration(
            shape: BoxShape.circle,
            color: Colors.white,
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(0.2),
                blurRadius: 2,
                offset: const Offset(0, 1),
              ),
            ],
          ),
        ),
      ),
    );
  }


  Widget _buildBackgroundGradients() {
    return Stack(
      children: [
        Positioned.fill(
          child: Container(
            color: GlassColors.ink,
          ),
        ),
        Positioned(
          left: -150,
          top: -150,
          width: 400,
          height: 400,
          child: Container(
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              gradient: RadialGradient(
                colors: [
                  GlassColors.accent.withOpacity(0.12),
                  GlassColors.accent.withOpacity(0.0),
                ],
              ),
            ),
          ),
        ),
        Positioned(
          right: -150,
          bottom: -150,
          width: 500,
          height: 500,
          child: Container(
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              gradient: RadialGradient(
                colors: [
                  GlassColors.purple.withOpacity(0.08),
                  GlassColors.teal.withOpacity(0.06),
                  GlassColors.teal.withOpacity(0.0),
                ],
                stops: const [0.0, 0.5, 1.0],
              ),
            ),
          ),
        ),
      ],
    );
  }

  String _getDeviceIcon(String deviceName) {
    final name = deviceName.toLowerCase();
    if (name.contains('linux') || name.contains('pc') || name.contains('desktop') || name.contains('windows') || name.contains('macos')) {
      return AppIcons.desktopDevice;
    } else if (name.contains('android') || name.contains('phone')) {
      return AppIcons.phoneDevice;
    } else if (name.contains('ipad') || name.contains('ios') || name.contains('client')) {
      return AppIcons.ipadDevice;
    }
    return AppIcons.unknownDevice;
  }

  // View Panes
  Widget _buildDevicesPane() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        // Manual Connection Card
        GlassCard(
          margin: const EdgeInsets.only(bottom: 12),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  _renderSvg(AppIcons.connect, size: 16, color: GlassColors.accent),
                  const SizedBox(width: 8),
                  const Text(
                    "MANUAL CONNECTION",
                    style: TextStyle(
                      fontSize: 11,
                      fontWeight: FontWeight.bold,
                      color: GlassColors.t2,
                      letterSpacing: 1.0,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 10),
              Row(
                children: [
                  Expanded(
                    child: SizedBox(
                      height: 38,
                      child: TextField(
                        controller: _manualIpController,
                        style: const TextStyle(color: GlassColors.t1, fontSize: 13),
                        decoration: InputDecoration(
                          hintText: 'Enter IP (e.g. 192.168.43.10)',
                          hintStyle: const TextStyle(color: GlassColors.t3, fontSize: 13),
                          filled: true,
                          fillColor: const Color(0x0DFFFFFF),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(8),
                            borderSide: const BorderSide(color: Color(0x17FFFFFF)),
                          ),
                          enabledBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(8),
                            borderSide: const BorderSide(color: Color(0x17FFFFFF)),
                          ),
                          focusedBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(8),
                            borderSide: const BorderSide(color: GlassColors.accent),
                          ),
                          contentPadding: const EdgeInsets.symmetric(horizontal: 10, vertical: 8),
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(width: 8),
                  ElevatedButton.icon(
                    onPressed: () {
                      final ip = _manualIpController.text.trim();
                      if (ip.isEmpty) return;
                      _log("Initiating manual pairing to $ip...");
                      api.initiatePairingToIp(ipOrAddr: ip);
                    },
                    icon: const Icon(Icons.add_link, size: 16),
                    label: const Text("Connect", style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold)),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: GlassColors.accent,
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                      elevation: 0,
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
        
        // Title
        const Padding(
          padding: EdgeInsets.only(left: 4, bottom: 8),
          child: Text(
            "DISCOVERED DEVICES",
            style: TextStyle(
              fontSize: 11,
              fontWeight: FontWeight.bold,
              color: GlassColors.t3,
              letterSpacing: 1.0,
            ),
          ),
        ),
        
        // List
        Expanded(
          child: _discoveredPeers.isEmpty
              ? Center(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      _renderSvg(AppIcons.search, size: 36, color: GlassColors.t3),
                      const SizedBox(height: 12),
                      const Text(
                        "No devices discovered yet",
                        style: TextStyle(color: GlassColors.t2, fontSize: 13),
                      ),
                    ],
                  ),
                )
              : ListView.builder(
                  itemCount: _discoveredPeers.length,
                  itemBuilder: (context, index) {
                    final peer = _discoveredPeers[index];
                    final isTrusted = _isPeerTrusted(peer.deviceId);
                    final deviceIcon = _getDeviceIcon(peer.deviceName);

                    return GlassCard(
                      margin: const EdgeInsets.symmetric(vertical: 4),
                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                      child: Row(
                        children: [
                          _renderSvg(deviceIcon, size: 28),
                          const SizedBox(width: 12),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  peer.deviceName.isEmpty ? "Unknown Peer" : peer.deviceName,
                                  style: const TextStyle(fontWeight: FontWeight.bold, color: GlassColors.t1),
                                ),
                                const SizedBox(height: 2),
                                Text(
                                  '${peer.ipAddress}:${peer.wsPort} • Status: ${peer.connectionStatus}',
                                  style: const TextStyle(color: GlassColors.t2, fontSize: 11),
                                ),
                              ],
                            ),
                          ),
                          const SizedBox(width: 8),
                          isTrusted
                              ? Container(
                                  padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                                  decoration: BoxDecoration(
                                    color: GlassColors.green2,
                                    borderRadius: BorderRadius.circular(12),
                                    border: Border.all(color: GlassColors.green.withOpacity(0.3)),
                                  ),
                                  child: const Row(
                                    children: [
                                      Icon(Icons.shield, color: GlassColors.green, size: 12),
                                      SizedBox(width: 4),
                                      Text(
                                        "Paired",
                                        style: TextStyle(color: GlassColors.green, fontSize: 10, fontWeight: FontWeight.bold),
                                      ),
                                    ],
                                  ),
                                )
                              : ElevatedButton(
                                  onPressed: () {
                                    _log("Sending pairing request to ${peer.deviceName}...");
                                    api.initiatePairing(peerId: peer.deviceId);
                                  },
                                  style: ElevatedButton.styleFrom(
                                    backgroundColor: GlassColors.amber2,
                                    foregroundColor: GlassColors.amber,
                                    side: BorderSide(color: GlassColors.amber.withOpacity(0.3)),
                                    padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                                    elevation: 0,
                                  ),
                                  child: const Text("Pair Device", style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold)),
                                ),
                        ],
                      ),
                    );
                  },
                ),
        ),
      ],
    );
  }

  Widget _buildTrustedPane() {
    if (_trustedPeers.isEmpty) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            _renderSvg(AppIcons.trusted, size: 36, color: GlassColors.t3),
            const SizedBox(height: 12),
            const Text(
              "No trusted peers registered",
              style: TextStyle(color: GlassColors.t2, fontSize: 13),
            ),
          ],
        ),
      );
    }

    return ListView.builder(
      itemCount: _trustedPeers.length,
      itemBuilder: (context, index) {
        final peer = _trustedPeers[index];

        return GlassCard(
          margin: const EdgeInsets.symmetric(vertical: 4),
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
          child: Row(
            children: [
              _renderSvg(AppIcons.trusted, size: 24, color: GlassColors.green),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      peer.deviceName,
                      style: const TextStyle(fontWeight: FontWeight.bold, color: GlassColors.t1),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      'FP: ${peer.fingerprint}',
                      style: const TextStyle(fontSize: 10, fontFamily: 'monospace', color: GlassColors.amber),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      'ID: ${peer.deviceId}',
                      style: const TextStyle(fontSize: 10, color: GlassColors.t2, fontFamily: 'monospace'),
                    ),
                  ],
                ),
              ),
              IconButton(
                icon: _renderSvg(AppIcons.trash, size: 18, color: GlassColors.red),
                onPressed: () {
                  _showUnpairConfirmation(peer.deviceId, peer.deviceName);
                },
              ),
            ],
          ),
        );
      },
    );
  }

  void _showUnpairConfirmation(String peerId, String name) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: const Color(0xFF0F172A),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(16),
          side: const BorderSide(color: Color(0x1CFFFFFF)),
        ),
        title: const Text("Confirm Unpair", style: TextStyle(color: GlassColors.t1)),
        content: Text(
          "Are you sure you want to unpair from $name? Secure sessions will be immediately terminated.",
          style: const TextStyle(color: GlassColors.t2),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text("Cancel", style: TextStyle(color: GlassColors.t2)),
          ),
          ElevatedButton(
            onPressed: () {
              api.unpairDevice(peerId: peerId);
              Navigator.pop(context);
              _log("Device $name unpaired and untrusted.");
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: GlassColors.red,
              foregroundColor: Colors.white,
              elevation: 0,
            ),
            child: const Text("Unpair"),
          ),
        ],
      ),
    );
  }

  Widget _buildLogsPane() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        const Padding(
          padding: EdgeInsets.only(left: 4, bottom: 8),
          child: Text(
            "SECURITY & SYNC LOGS",
            style: TextStyle(
              fontSize: 11,
              fontWeight: FontWeight.bold,
              color: GlassColors.t3,
              letterSpacing: 1.0,
            ),
          ),
        ),
        Expanded(
          child: GlassCard(
            deep: true,
            padding: const EdgeInsets.all(8),
            child: _logs.isEmpty
                ? const Center(
                    child: Text(
                      "Empty console logs",
                      style: TextStyle(color: GlassColors.t3, fontSize: 11),
                    ),
                  )
                : ListView.builder(
                    itemCount: _logs.length,
                    itemBuilder: (context, index) {
                      return Padding(
                        padding: const EdgeInsets.symmetric(vertical: 2.0),
                        child: Text(
                          _logs[index],
                          style: const TextStyle(
                            fontFamily: 'monospace',
                            fontSize: 11,
                            color: Color(0xFF38BDF8),
                          ),
                        ),
                      );
                    },
                  ),
          ),
        ),
      ],
    );
  }

  Widget _buildSettingsPane() {
    return ListView(
      children: [
        const Padding(
          padding: EdgeInsets.only(left: 4, bottom: 8),
          child: Text(
            "DEVICE CONFIGURATION",
            style: TextStyle(
              fontSize: 11,
              fontWeight: FontWeight.bold,
              color: GlassColors.t3,
              letterSpacing: 1.0,
            ),
          ),
        ),
        GlassCard(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text(
                          "Local Device Name",
                          style: TextStyle(color: GlassColors.t2, fontSize: 12),
                        ),
                        const SizedBox(height: 6),
                        SizedBox(
                          height: 38,
                          child: TextField(
                            controller: _nameController,
                            enabled: !_isSyncEnabled,
                            style: const TextStyle(color: GlassColors.t1, fontSize: 14),
                            decoration: InputDecoration(
                              hintText: 'Enter device name',
                              hintStyle: const TextStyle(color: GlassColors.t3, fontSize: 13),
                              filled: true,
                              fillColor: const Color(0x0DFFFFFF),
                              border: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(8),
                                borderSide: const BorderSide(color: Color(0x17FFFFFF)),
                              ),
                              enabledBorder: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(8),
                                borderSide: const BorderSide(color: Color(0x17FFFFFF)),
                              ),
                              focusedBorder: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(8),
                                borderSide: const BorderSide(color: GlassColors.accent),
                              ),
                              contentPadding: const EdgeInsets.symmetric(horizontal: 10, vertical: 8),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(width: 24),
                  Column(
                    children: [
                      const Text(
                        'SECURE SYNC',
                        style: TextStyle(fontSize: 10, fontWeight: FontWeight.bold, color: GlassColors.t2),
                      ),
                      const SizedBox(height: 6),
                      _buildCustomToggle(
                        value: _isSyncEnabled,
                        onChanged: _toggleSync,
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ),
        const SizedBox(height: 12),
        const Padding(
          padding: EdgeInsets.only(left: 4, bottom: 8),
          child: Text(
            "SYSTEM METRICS",
            style: TextStyle(
              fontSize: 11,
              fontWeight: FontWeight.bold,
              color: GlassColors.t3,
              letterSpacing: 1.0,
            ),
          ),
        ),
        GlassCard(
          child: Column(
            children: [
              _buildMetricRow("LAN IP Address", _localIp),
              const Divider(color: Color(0x17FFFFFF), height: 16),
              _buildMetricRow("Device ID", _deviceId, monospace: true),
              const Divider(color: Color(0x17FFFFFF), height: 16),
              _buildMetricRow("App Lifecycle", _lifecycleState),
              const Divider(color: Color(0x17FFFFFF), height: 16),
              _buildMetricRow("Last Network Sync", _lastSyncTimestamp),
              const Divider(color: Color(0x17FFFFFF), height: 16),
              _buildMetricRow("E2EE Fingerprint", _myFingerprint, monospace: true, small: true),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildMetricRow(String label, String value, {bool monospace = false, bool small = false}) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(label, style: const TextStyle(color: GlassColors.t2, fontSize: 13)),
        Flexible(
          child: Text(
            value,
            style: TextStyle(
              color: GlassColors.t1,
              fontSize: small ? 11 : 13,
              fontFamily: monospace ? 'monospace' : null,
            ),
            overflow: TextOverflow.ellipsis,
            textAlign: TextAlign.end,
          ),
        ),
      ],
    );
  }

  Widget _buildActivePane() {
    switch (_activeNavIndex) {
      case 0:
        return _buildDevicesPane();
      case 1:
        return _buildTrustedPane();
      case 2:
        return _buildLogsPane();
      case 3:
        return _buildSettingsPane();
      default:
        return _buildDevicesPane();
    }
  }

  // Layout Builders
  Widget _buildPhoneLayout() {
    return Column(
      children: [
        Expanded(
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 12.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                _buildIdentityCard(),
                const SizedBox(height: 16),
                Expanded(
                  child: _buildActivePane(),
                ),
              ],
            ),
          ),
        ),
        _buildPhoneBottomNavigationBar(),
      ],
    );
  }

  Widget _buildIdentityCard() {
    return GlassCard(
      padding: const EdgeInsets.all(12),
      child: Column(
        children: [
          Row(
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10),
                child: Image.asset(
                  'assets/logo.png',
                  width: 38,
                  height: 38,
                  fit: BoxFit.cover,
                ),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      _nameController.text.isEmpty ? "AirBoard" : _nameController.text,
                      style: const TextStyle(
                        fontWeight: FontWeight.bold,
                        fontSize: 16,
                        color: GlassColors.t1,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Row(
                      children: [
                        _renderSvg(AppIcons.fingerprint, size: 12, color: GlassColors.t2),
                        const SizedBox(width: 4),
                        Expanded(
                          child: Text(
                            _myFingerprint.length > 20
                                ? '${_myFingerprint.substring(0, 20)}...'
                                : _myFingerprint,
                            style: const TextStyle(
                              fontSize: 10,
                              color: GlassColors.t2,
                              fontFamily: 'monospace',
                            ),
                            overflow: TextOverflow.ellipsis,
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
              // Frosted device info pill
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                decoration: BoxDecoration(
                  color: const Color(0x1AFFFFFF),
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: const Color(0x14FFFFFF)),
                ),
                child: Row(
                  children: [
                    PulsingDot(
                      color: _isSyncEnabled ? GlassColors.green : Colors.grey,
                      size: 6.0,
                    ),
                    const SizedBox(width: 6),
                    Text(
                      _isSyncEnabled ? "E2EE ACTIVE" : "OFFLINE",
                      style: TextStyle(
                        fontSize: 9,
                        fontWeight: FontWeight.bold,
                        color: _isSyncEnabled ? GlassColors.green : GlassColors.t2,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
          
          // Inner Segmented tab bar inside the identity card
          const SizedBox(height: 12),
          Container(
            height: 32,
            padding: const EdgeInsets.all(2),
            decoration: BoxDecoration(
              color: const Color(0x0DFFFFFF),
              borderRadius: BorderRadius.circular(8),
            ),
            child: Row(
              children: [
                _buildIdentityTabItem(0, "Devices"),
                _buildIdentityTabItem(1, "Trusted"),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildIdentityTabItem(int index, String label) {
    final isSelected = _activeNavIndex == index;
    return Expanded(
      child: GestureDetector(
        onTap: () {
          setState(() {
            _activeNavIndex = index;
          });
        },
        child: Container(
          decoration: BoxDecoration(
            color: isSelected ? const Color(0x1AFFFFFF) : Colors.transparent,
            borderRadius: BorderRadius.circular(6),
          ),
          alignment: Alignment.center,
          child: Text(
            label,
            style: TextStyle(
              fontSize: 12,
              fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
              color: isSelected ? GlassColors.t1 : GlassColors.t2,
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildPhoneBottomNavigationBar() {
    return Container(
      height: 60,
      decoration: const BoxDecoration(
        color: Color(0x0FFFFFFF), // Glass
        border: Border(
          top: BorderSide(color: Color(0x1CFFFFFF), width: 1.0),
        ),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: [
          _buildBottomNavButton(0, "Devices", AppIcons.devices),
          _buildBottomNavButton(1, "Trusted", AppIcons.trusted),
          _buildBottomNavButton(2, "Logs", AppIcons.logs),
          _buildBottomNavButton(3, "Settings", AppIcons.settings),
        ],
      ),
    );
  }

  Widget _buildBottomNavButton(int index, String label, String svgIcon) {
    final isSelected = _activeNavIndex == index;
    return Expanded(
      child: InkWell(
        onTap: () {
          setState(() {
            _activeNavIndex = index;
          });
        },
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            AnimatedScale(
              scale: isSelected ? 1.1 : 1.0,
              duration: const Duration(milliseconds: 150),
              child: _renderSvg(
                svgIcon,
                size: 20,
                color: isSelected ? GlassColors.accent : GlassColors.t2,
              ),
            ),
            const SizedBox(height: 4),
            Text(
              label,
              style: TextStyle(
                fontSize: 10,
                fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
                color: isSelected ? GlassColors.accent : GlassColors.t2,
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildTabletLayout() {
    return Row(
      children: [
        // Persistent Left Sidebar
        Container(
          width: 200,
          decoration: const BoxDecoration(
            color: Color(0x0FFFFFFF), // Glass
            border: Border(
              right: BorderSide(color: Color(0x1CFFFFFF), width: 1.0),
            ),
          ),
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Logo / Title
              Row(
                children: [
                  ClipRRect(
                    borderRadius: BorderRadius.circular(6),
                    child: Image.asset(
                      'assets/logo.png',
                      width: 24,
                      height: 24,
                      fit: BoxFit.cover,
                    ),
                  ),
                  const SizedBox(width: 8),
                  const Text(
                    "AirBoard",
                    style: TextStyle(
                      fontWeight: FontWeight.bold,
                      fontSize: 16,
                      color: GlassColors.t1,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 24),
              // Navigation Section
              const Text(
                "NAVIGATION",
                style: TextStyle(
                  fontSize: 10,
                  color: GlassColors.t3,
                  fontWeight: FontWeight.bold,
                  letterSpacing: 1.0,
                ),
              ),
              const SizedBox(height: 8),
              _buildSidebarNavItem(0, "Devices", AppIcons.devices),
              _buildSidebarNavItem(1, "Trusted Peers", AppIcons.trusted),
              _buildSidebarNavItem(2, "Event Logs", AppIcons.logs),
              _buildSidebarNavItem(3, "Settings", AppIcons.settings),
              const Spacer(),
              // Frosted device info pill at bottom
              Container(
                padding: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  color: const Color(0x0DFFFFFF),
                  borderRadius: BorderRadius.circular(10),
                  border: Border.all(color: const Color(0x17FFFFFF)),
                ),
                child: Row(
                  children: [
                    PulsingDot(
                      color: _isSyncEnabled ? GlassColors.green : Colors.grey,
                      size: 6.0,
                    ),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        _isSyncEnabled ? "E2EE ACTIVE" : "OFFLINE",
                        style: TextStyle(
                          fontSize: 10,
                          fontWeight: FontWeight.bold,
                          color: _isSyncEnabled ? GlassColors.green : GlassColors.t2,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
        
        // Main Body
        Expanded(
          child: Padding(
            padding: const EdgeInsets.all(20.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Segmented Topbar Control
                Container(
                  height: 40,
                  padding: const EdgeInsets.all(3),
                  decoration: BoxDecoration(
                    color: const Color(0x0DFFFFFF),
                    borderRadius: BorderRadius.circular(10),
                  ),
                  child: Row(
                    children: [
                      _buildSegmentedItem(0, "Devices"),
                      _buildSegmentedItem(1, "Trusted"),
                      _buildSegmentedItem(2, "Logs"),
                      _buildSegmentedItem(3, "Settings"),
                    ],
                  ),
                ),
                const SizedBox(height: 20),
                Expanded(
                  child: _buildActivePane(),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildSidebarNavItem(int index, String label, String svgIcon) {
    final isSelected = _activeNavIndex == index;
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4.0),
      child: InkWell(
        onTap: () {
          setState(() {
            _activeNavIndex = index;
          });
        },
        borderRadius: BorderRadius.circular(8),
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
          decoration: BoxDecoration(
            color: isSelected ? const Color(0x1AFFFFFF) : Colors.transparent,
            borderRadius: BorderRadius.circular(8),
          ),
          child: Row(
            children: [
              _renderSvg(
                svgIcon,
                size: 18,
                color: isSelected ? GlassColors.accent : GlassColors.t2,
              ),
              const SizedBox(width: 10),
              Expanded(
                child: Text(
                  label,
                  style: TextStyle(
                    fontSize: 13,
                    fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
                    color: isSelected ? GlassColors.t1 : GlassColors.t2,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSegmentedItem(int index, String label) {
    final isSelected = _activeNavIndex == index;
    return Expanded(
      child: GestureDetector(
        onTap: () {
          setState(() {
            _activeNavIndex = index;
          });
        },
        child: Container(
          decoration: BoxDecoration(
            color: isSelected ? const Color(0x1AFFFFFF) : Colors.transparent,
            borderRadius: BorderRadius.circular(7),
          ),
          alignment: Alignment.center,
          child: Text(
            label,
            style: TextStyle(
              fontSize: 12,
              fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
              color: isSelected ? GlassColors.t1 : GlassColors.t2,
            ),
          ),
        ),
      ),
    );
  }  Widget _buildDesktopLayout() {
    return Row(
      children: [
        // Left Sidebar
        Container(
          width: 220,
          decoration: const BoxDecoration(
            color: Color(0x05FFFFFF),
            border: Border(
              right: BorderSide(color: Color(0x1CFFFFFF), width: 1.0),
            ),
          ),
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Row(
                children: [
                  ClipRRect(
                    borderRadius: BorderRadius.circular(6),
                    child: Image.asset(
                      'assets/logo.png',
                      width: 28,
                      height: 28,
                      fit: BoxFit.cover,
                    ),
                  ),
                  const SizedBox(width: 10),
                  const Text(
                    "AirBoard",
                    style: TextStyle(
                      fontWeight: FontWeight.bold,
                      fontSize: 18,
                      color: GlassColors.t1,
                      letterSpacing: -0.5,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 28),
              
              // NETWORK section
              const Text(
                "NETWORK",
                style: TextStyle(
                  fontSize: 9,
                  color: GlassColors.t3,
                  fontWeight: FontWeight.bold,
                  letterSpacing: 1.2,
                ),
              ),
              const SizedBox(height: 6),
              _buildSidebarNavItem(0, "Devices Discovered", AppIcons.devices),
              _buildSidebarNavItem(1, "Trusted Peers", AppIcons.trusted),
              
              const SizedBox(height: 20),
              
              // SYSTEM section
              const Text(
                "SYSTEM",
                style: TextStyle(
                  fontSize: 9,
                  color: GlassColors.t3,
                  fontWeight: FontWeight.bold,
                  letterSpacing: 1.2,
                ),
              ),
              const SizedBox(height: 6),
              _buildSidebarNavItem(2, "Security Logs", AppIcons.logs),
              _buildSidebarNavItem(3, "Settings", AppIcons.settings),
              
              const Spacer(),
              
              // Connection pill at bottom
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: const Color(0x0FFFFFFF),
                  borderRadius: BorderRadius.circular(10),
                  border: Border.all(color: const Color(0x1CFFFFFF)),
                ),
                child: Row(
                  children: [
                    PulsingDot(
                      color: _isSyncEnabled ? GlassColors.green : Colors.grey,
                      size: 6.0,
                    ),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        _isSyncEnabled ? "SECURE SYNC" : "OFFLINE",
                        style: TextStyle(
                          fontSize: 9,
                          fontWeight: FontWeight.bold,
                          color: _isSyncEnabled ? GlassColors.green : GlassColors.t2,
                          letterSpacing: 0.5,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
        
        // Content Area + Stats Row
        Expanded(
          child: Padding(
            padding: const EdgeInsets.all(24.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Stats Row
                Row(
                  children: [
                    Expanded(
                      child: _buildStatCard(
                        "DEVICES DISCOVERED",
                        "${_discoveredPeers.length}",
                        _renderSvg(AppIcons.devices, size: 20, color: GlassColors.accent),
                        GlassColors.accent,
                      ),
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: _buildStatCard(
                        "TRUSTED PEERS",
                        "${_trustedPeers.length}",
                        _renderSvg(AppIcons.trusted, size: 20, color: GlassColors.green),
                        GlassColors.green,
                      ),
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: _buildStatCard(
                        "LAST SYNC",
                        _lastSyncTimestamp,
                        _renderSvg(AppIcons.syncOn, size: 20, color: GlassColors.purple),
                        GlassColors.purple,
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 24),
                Expanded(
                  child: _buildActivePane(),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildStatCard(String label, String value, Widget iconWidget, Color accentColor) {
    return GlassCard(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: accentColor.withOpacity(0.08),
              borderRadius: BorderRadius.circular(8),
              border: Border.all(color: accentColor.withOpacity(0.2)),
            ),
            child: iconWidget,
          ),
          const SizedBox(width: 14),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  label,
                  style: const TextStyle(
                    fontSize: 10,
                    fontWeight: FontWeight.bold,
                    color: GlassColors.t3,
                    letterSpacing: 0.8,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  value,
                  style: const TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                    color: GlassColors.t1,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          _buildBackgroundGradients(),
          SafeArea(
            child: LayoutBuilder(
              builder: (context, constraints) {
                if (constraints.maxWidth < 600) {
                  return _buildPhoneLayout();
                } else if (constraints.maxWidth < 900) {
                  return _buildTabletLayout();
                } else {
                  return _buildDesktopLayout();
                }
              },
            ),
          ),
        ],
      ),
    );
  }
}

// Glassmorphism Utility Widgets
class GlassCard extends StatelessWidget {
  final Widget child;
  final EdgeInsetsGeometry? padding;
  final EdgeInsetsGeometry? margin;
  final double borderRadius;
  final bool deep;

  const GlassCard({
    super.key,
    required this.child,
    this.padding = const EdgeInsets.all(14.0),
    this.margin,
    this.borderRadius = 12.0,
    this.deep = false,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: margin,
      padding: padding,
      decoration: BoxDecoration(
        color: deep ? const Color(0x59000000) : const Color(0x0FFFFFFF),
        border: Border.all(
          color: deep ? const Color(0x14FFFFFF) : const Color(0x1CFFFFFF),
          width: 1.0,
        ),
        borderRadius: BorderRadius.circular(borderRadius),
      ),
      child: child,
    );
  }
}

class PulsingDot extends StatefulWidget {
  final Color color;
  final double size;

  const PulsingDot({
    super.key,
    this.color = const Color(0xFF30D158),
    this.size = 8.0,
  });

  @override
  State<PulsingDot> createState() => _PulsingDotState();
}

class _PulsingDotState extends State<PulsingDot> with SingleTickerProviderStateMixin {
  late AnimationController _controller;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(
      vsync: this,
      duration: const Duration(seconds: 2),
    )..repeat();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: _controller,
      builder: (context, child) {
        return Stack(
          alignment: Alignment.center,
          children: [
            Container(
              width: widget.size * (1 + _controller.value * 1.5),
              height: widget.size * (1 + _controller.value * 1.5),
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                color: widget.color.withOpacity((1.0 - _controller.value) * 0.4),
              ),
            ),
            Container(
              width: widget.size,
              height: widget.size,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                color: widget.color,
              ),
            ),
          ],
        );
      },
    );
  }
}
