// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Peer {
  final String deviceId;
  final String deviceName;
  final String ipAddress;
  final int wsPort;
  final BigInt lastSeen;
  final String connectionStatus;

  const Peer({
    required this.deviceId,
    required this.deviceName,
    required this.ipAddress,
    required this.wsPort,
    required this.lastSeen,
    required this.connectionStatus,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      deviceName.hashCode ^
      ipAddress.hashCode ^
      wsPort.hashCode ^
      lastSeen.hashCode ^
      connectionStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Peer &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          ipAddress == other.ipAddress &&
          wsPort == other.wsPort &&
          lastSeen == other.lastSeen &&
          connectionStatus == other.connectionStatus;
}
