// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'engine.freezed.dart';

@freezed
sealed class SyncEvent with _$SyncEvent {
  const SyncEvent._();

  const factory SyncEvent.clipboardUpdated({
    required String content,
  }) = SyncEvent_ClipboardUpdated;
  const factory SyncEvent.connectionStatus({
    required bool connected,
    required String message,
  }) = SyncEvent_ConnectionStatus;
  const factory SyncEvent.error({
    required String message,
  }) = SyncEvent_Error;
}
